name: test

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
      - '!develop'
      - '!release/**'
      - '!gh-pages'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: npm install
      - run: npm install --save @babel/cli @babel/preset-typescript
      - run: npm run test
